name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'yarn'

      # allow the lock file to change (updating our own workspace versions in monorepo)
      - run: yarn install --no-immutable
      # - run: yarn build
      # - run: yarn test

      # commit back the lock file change if it works
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply yarn.lock changes

      # publishes canaries and releases to github
      - run: yarn release

      # cannot run this on branches because it doesn't keep the canary version from auto shipit, can only secondarily publish to npm for main branch
      - name: Publish secondarily to npm
        run: npm publish --access=public --ignore-scripts --@alienfast:registry='https://registry.npmjs.org'
        if: github.ref == 'refs/heads/main'
